In [1]:
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
def get_t():
    labels_path = os.path.join('Train', 'Training Labels.txt')
    with open(labels_path) as f:
        training_labels = [int(x) for x in f.read().splitlines()]
    return np.array(training_labels)

In [68]:
def get_x():
    sorted_file_names = sorted([x for x in os.listdir('Train') if x.endswith('.jpg')], key=lambda x: int(x[:-4]))

    image_paths = [os.path.join('Train', x) for x in sorted_file_names]
    x_input_points = np.zeros((0, 784))
    for img in image_paths:
        x_input_points = np.append(x_input_points, plt.imread(img).reshape(1, 784), axis=0)

    return x_input_points

In [75]:
x = get_x()
print('x: ', x.shape)
t = get_t()
print('t: ', t.shape)

x:  (2400, 784)
t:  (2400,)


In [70]:
x_delta = np.append(x, np.ones((x.shape[0], 1)), axis=1)
x_delta, x_delta.shape

(array([[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.]]), (2400, 785))

In [71]:
# A_matrix is just an intermediate to avoid re-calculation for each class
A_matrix = np.dot(np.linalg.pinv(np.dot(x_delta.T, x_delta)), x_delta.T)
A_matrix, A_matrix.shape

(array([[-5.63795047e-04, -7.88938722e-04, -2.51576124e-04, ...,
         -4.95694154e-04, -1.08647390e-04, -9.07576247e-05],
        [-3.41037060e-04,  1.40580204e-04, -4.44138414e-04, ...,
          9.10748826e-05,  2.33016815e-05,  2.75897560e-05],
        [-5.64795652e-04,  1.74178402e-04, -1.11366877e-04, ...,
          2.98258500e-04, -8.67689842e-04,  6.37789926e-05],
        ...,
        [-1.75748230e-04,  1.43494005e-06, -2.81809242e-05, ...,
         -7.59919987e-05, -4.65864194e-04,  9.46179762e-05],
        [ 1.00420013e-04, -1.61052896e-04, -1.34171277e-04, ...,
         -1.61592292e-04,  4.34180377e-04, -1.21774605e-04],
        [ 1.59047786e-03,  1.57917926e-03,  9.43402145e-04, ...,
          4.23254769e-03, -1.59497339e-03,  6.36501164e-03]]), (785, 2400))

In [76]:
# Labels matrix (), each row representing one class, and the columns represent the true label of each image 
T = np.zeros((10, 2400))
for i in range(len(T)):
    T[i] = np.where(t == i, 1, -1)
T.shape

(10, 2400)

In [99]:
# wc_3 = np.dot(A_matrix, t_3)
# weights_matrix = [None] * 10
# for i in range(len(weights_matrix)):
#     weights_matrix[i] = np.dot(A_matrix, T[i])

# WC = np.vstack((weights_matrix)).T
# WC, WC.shape

weights_matrix = np.zeros((785, 10))
for i in range(10):
    # Set each col. as the weight vector in index i.
    weights_matrix[:,i] = np.dot(A_matrix, T[i])

weights_matrix, weights_matrix.shape

(array([[-1.28122634e-02, -1.04062050e-02,  2.11384103e-02, ...,
          4.61245558e-03, -1.15395581e-02, -8.35871834e-03],
        [-8.20818997e-03, -1.27681691e-02, -1.79094082e-02, ...,
          8.55325381e-03,  1.82555742e-02, -2.50475252e-02],
        [-1.28384850e-02, -1.41128185e-02, -2.12430908e-02, ...,
          1.67946959e-02,  9.80420930e-03, -1.50468826e-02],
        ...,
        [-5.64247937e-04,  2.67185494e-04, -6.29812154e-03, ...,
         -4.27307909e-05,  5.57044346e-03, -3.79859912e-03],
        [-1.84230940e-03,  8.58858661e-04, -2.88541430e-03, ...,
         -6.67152393e-03,  1.45686724e-03,  3.44808727e-03],
        [-5.98916042e-01, -4.50061325e-01, -9.48247004e-01, ...,
         -7.56519387e-01, -1.19480465e+00, -8.29974078e-01]]), (785, 10))

In [104]:
out = np.dot(x_delta, WC)
WC.shape

(785, 10)

In [110]:
tested = out[1000]
pred = np.where(zero == zero.max())
pred, pred[0][0]

((array([4]),), 4)

In [67]:
out.shape

(2400, 10)